name: Release
run-name: '[${{ github.ref_name }}] triggered by [${{ github.event_name }}/${{ github.actor }}]'

on:
  push:
    branches: '*'
  workflow_dispatch:

jobs:
  publish:
    uses: krauters/shared-workflows/.github/workflows/release.yaml@main
    secrets:
      GH_TOKEN_RELEASES: ${{ secrets.GH_TOKEN_RELEASES }}
